// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqsjagyedrldhiggpjms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxc2phZ3llZHJsZGhpZ2dwam1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NTA0ODEsImV4cCI6MjA2ODMyNjQ4MX0.Ru71guPX40MJ40zLZUDaVR8wUsUkZkjJAcUODv3NdV0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});